name: Java Weekly Update
on:
  schedule:
    - cron: '0 12 * * 1'  # 每周一12:00（UTC）
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Java Application
        run: java -jar target/april-github-star-list-jar-with-dependencies.jar

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: git pull origin main --rebase

      - name: Commit changes
        run: |
          git add .
          git commit -m ":sparkles: weekly update - $(date +'%Y-%m-%d')" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main

      - name: Verify repo.md exists
        id: verify_file
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          if [ -f "repo.md" ]; then
            echo "repo.md file exists with size: $(wc -l < repo.md) lines"
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "repo.md file does not exist"
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Send email via QQ Mail
        if: steps.verify_file.outputs.file_exists == 'true' && secrets.TO_EMAIL != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.QQ_EMAIL }}
          password: ${{ secrets.QQ_EMAIL_PASSWORD }}
          subject: 'Weekly Java Update - $(date +%Y-%m-%d)'
          to: ${{ secrets.TO_EMAIL }}
          from: GitHub Actions
          body: |
            Hello,
            
            Please find attached the weekly repo.md update.
            
            This email was automatically generated by GitHub Actions.
          attachments: ./repo.md
          secure: true

      - name: Create and send alternative if repo.md missing
        if: steps.verify_file.outputs.file_exists == 'false' && secrets.TO_EMAIL != ''
        run: |
          echo "Creating alternative file since repo.md is missing..."
          echo "Weekly Update - $(date +'%Y-%m-%d')" > weekly-update.txt
          echo "No repo.md file was generated this week." >> weekly-update.txt
          echo "Please check the GitHub Actions logs for more details." >> weekly-update.txt
        continue-on-error: true

      - name: Send alternative email
        if: steps.verify_file.outputs.file_exists == 'false' && secrets.TO_EMAIL != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.QQ_EMAIL }}
          password: ${{ secrets.QQ_EMAIL_PASSWORD }}
          subject: 'Weekly Java Update - $(date +%Y-%m-%d) - ALERT: No repo.md'
          to: ${{ secrets.TO_EMAIL }}
          from: GitHub Actions
          body: |
            ALERT: The repo.md file was not generated this week.
            
            Please check the GitHub Actions workflow for errors.
            
            This email was automatically generated by GitHub Actions.
          attachments: ./weekly-update.txt
          secure: true