name: Java Weekly Update

on:
  schedule:
    - cron: '0 12 * * 1'  # 每周一12:00（UTC）
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: git pull origin main

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Java Application
        run: java -jar target/april-github-star-list-jar-with-dependencies.jar

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "weekly update - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main

      - name: Verify repo.md exists
        id: verify_file
        run: |
          if [ -f "repo.md" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
            echo "File exists with $(wc -l < repo.md) lines"
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
            echo "File does not exist"
          fi

      - name: Send email via QQ Mail
        if: steps.verify_file.outputs.file_exists == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.QQ_EMAIL }}
          password: ${{ secrets.QQ_EMAIL_PASSWORD }}
          subject: 'Weekly Java Update'
          to: ${{ secrets.TO_EMAIL }}
          from: GitHub Actions
          body: 'Please find attached the weekly repo.md update.'
          attachments: repo.md
          secure: true